### ISSUE TITLE
Bug Report!? docker [exited 1] Export file does not exist (with fix)

### ISSUE THREAD

**Issue by crtvrmn** [bentasker/gadgetbridge_to_influxdb#1]
hey bentasker, 
i have been tinkering around with your awesome work for a few hours now and im learning quite a lot. right now i ran into a problem where the docker container exits with "Export file does not exist"

**tl: dr: change EXPORT_FILE=Gadgetbridge.db to EXPORT_FILENAME=Gadgetbridge.db in the docker-compose.yml**

**what i tried** 
- i made sure that the file really exists (it was 0b, now itws 400kb)
- test if its reachable: curl --user gadgetbridge:password -I http://192.168.178.3:8080/remote.php/dav/files/gadgetbridge/Gadgetbridge/Gadgetbridge.db (came back with 200 OK)
- ```  gadgetbridge-to-influxdb:
    image: bentasker12/gadgetbridge_to_influxdb:latest
    environment:
      - WEBDAV_URL=http://192.168.178.3:8080/remote.php/dav
      - WEBDAV_USER=gadgetbridge
      - WEBDAV_PASS=password
      - WEBDAV_PATH=files/gadgetbridge/Gadgetbridge/
      - EXPORT_FILE=Gadgetbridge.db #i even removed .db, didnt work 
      - QUERY_DURATION=86400
      - INFLUXDB_URL=192.168.178.3:8086
      - INFLUXDB_BUCKET=MAIN
      - INFLUXDB_MEASUREMENT=gadgetbridge
      - SLEEP_HOURS=0,1,2,3,4,5,6

- i checked the python code and found that: EXPORT_FILE = os.getenv("EXPORT_FILENAME", "gadgetbridge"), but the documentation claims to use EXPORT_FILE instead of EXPORT_FILENAME

**Comment by bentasker** [comment]
Whoops. Nice catch, thanks for letting me know!
